export const CONSTANTS = {
    years:['2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020'],
    typeListOfHighSchool:['unknown','public','private','public','charter','independent','catholic','na'],
    valueListOfReceivedAid:['unknown','yes','no','na'],
    valueListOfIsGrudated:[
        {key:'unknown', value:'Unknown'},
        {key:'yes', value:'Yes'},
        {key:'no', value:'No'},
        {key:'ged', value:'GED'},
        {key:'currently_enrolled', value:'Currently Enrolled'},
        {key:'na', value:'Did not attend high school'}
    ],
    valueListOfLocaion:[
        {key: "unknown", value: "Unknown"},
        {key: "na", value: "Did not attend college"},
        {key: "dc", value: "District of Columbia"},
        {key: "md", value: "Maryland"},
        {key: "va", value: "Virgina"},
        {key: "AL", value: "Alabama"},
        {key: "AK", value: "Alaska"},
        {key: "AZ", value: "Arizona"},
        {key: "AR", value: "Arkansas"},
        {key: "CA", value: "California"},
        {key: "CO", value: "Colorado"},
        {key: "CT", value: "Connecticut"},
        {key: "DE", value: "Delaware"},
        {key: "FL", value: "Florida"},
        {key: "GA", value: "Georgia"},
        {key: "HI", value: "Hawaii"},
        {key: "ID", value: "Idaho"},
        {key: "IL", value: "Illinois"},
        {key: "IN", value: "Indiana"},
        {key: "IA", value: "Iowa"},
        {key: "KS", value: "Kansas"},
        {key: "KY", value: "Kentucky"},
        {key: "LA", value: "Louisiana"},
        {key: "ME", value: "Maine"},
        {key: "MA", value: "Massachusetts"},
        {key: "MI", value: "Michigan"},
        {key: "MN", value: "Minnesota"},
        {key: "MS", value: "Mississippi"},
        {key: "MO", value: "Missouri"},
        {key: "MT", value: "Montana"},
        {key: "NE", value: "Nebraska"},
        {key: "NV", value: "Nevada"},
        {key: "NH", value: "New Hampshire"},
        {key: "NJ", value: "New Jersey"},
        {key: "NM", value: "New Mexico"},
        {key: "NY", value: "New York"},
        {key: "NC", value: "North Carolina"},
        {key: "ND", value: "North Dakota"},
        {key: "OH", value: "Ohio"},
        {key: "OK", value: "Oklahoma"},
        {key: "OR", value: "Oregon"},
        {key: "PA", value: "Pennsylvania"},
        {key: "RI", value: "Rhode Island"},
        {key: "SC", value: "South Carolina"},
        {key: "SD", value: "South Dakota"},
        {key: "TN", value: "Tennessee"},
        {key: "TX", value: "Texas"},
        {key: "UT", value: "Utah"},
        {key: "VT", value: "Vermont"},
        {key: "WA", value: "Washington"},
        {key: "WV", value: "West Virginia"},
        {key: "WI", value: "Wisconsin"},
        {key: "WY", value: "Wyoming"},
        {key: "other", value: "Other"},
    ],
    typeListOfCollege:[
        {key:'unknown', value:'Unknown'},
        {key:'two_year', value:'Two Year'},
        {key:'four_year', value:'Four Year'},
        {key:'trade', value:'Trade School'},
        {key:'na', value:'Did not attend college'}
    ],
    valueListOfScholarship:[
        {key:'unknown', value:'Unknown'},
        {key:'yes', value:'Yes'},
        {key:'no', value:'No'},
        {key:'na', value:'Did not attend college'}
    ],
    valueListOfDegree:[
        {key:'unknown', value:'Unknown'},
        {key:'certificate', value:'Certificate'},
        {key:'associates', value:"Associate's Degree" },
        {key:'bachelors', value:"Bachelor's Degree"},
        {key:'masters', value:"Master's Degree"},
        {key:'doctoral', value:"Doctorla Degree"},
        {key:'currently_enrolled', value:"Currently Enrolled"},
        {key:'no', value:'No'},
        {key:'na', value:'Did not attend college'}
    ],
    valueListOfBranchMilitary: [
        {key:'unknown', value:'Unknown'},
        {key:'na', value:'Did not enlist'},
        {key:'army', value:'Army'},
        {key:'navy', value:'Navy'},
        {key:'marine_corps', value:'Marine Corps'},
        {key:'air_force', value:'Air Force'},
        {key:'national_guard', value:'National Guard'}
    ],

    dashboardItems:[
        {key: "isContracted", value: "Has the student been contacted? "},
        {key: "isEngaged", value: "Has the student been engaged? "},
        {key: "isgrduateWJA", value: "Did the student graduate WJA? "},
        {key: "graduateWJA", value: "What year did the student graduate WJA?"},
        {key: "isAttendHighSchool", value: "Did the student attend high School?"},
        {key: "typeOfHighSchool", value: "What type of high school did the student attend?"},
        {key: "isReceivedAid", value: "Did the student receive aid for high school?"},
        {key: "isGraduated", value: "Did the student graduate high school?"},
        {key: "highschool_location", value: "Where is the high school located?"},
        {key: "isAttendCollege", value: "Did the student attend College?"},
        {key: "typeOfCollege", value: "What type of college did the student attend?"},
        {key: "isReceivedScholarship", value: "Did the student receive scholarships?"},
        {key: "isGraduatedCollege", value: "Did the Student graduate College?"},
        {key: "locationOfCollege", value: "Where is the college located?"},
        {key: "isEnlistMilitary", value: "Did the student enlist in the military?"},
        {key: "branchOfMilitary", value: " Which branch of the military?"},
        {key: "isEmployed", value: "Is the student employed??"}        
    ]
}
